# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.synced_folder ".", "/vagrant", type: "smb"
  config.vm.synced_folder "./shared_drive", "/vagrant", type: "rsync",
    rsync__exclude: ".git/"

  config.vm.define "admin" do |web|
    config.vm.box = "generic/ubuntu2204"
    config.vm.network "public_network", bridge: "Public Switch", use_dhcp_assigned_default_route: true
    config.vm.provider "hyperv" do |vb|
      # Customize the amount of memory on the VM:
      vb.maxmemory = "4096"
      vb.memory = "2048"
      vb.cpus = "2"
    end

    config.vm.provision "file", source: "../common/calico.yaml", destination: "calico.yaml"
    config.vm.provision "file", source: "../common/kubeadm-config.yaml", destination: "kubeadm-config.yaml"
    config.vm.provision "file", source: "../common/nginx.yaml", destination: "nginx.yaml"

    config.vm.provision "shell", path: "install.sh", keep_color: true
    config.vm.provision "shell", path: "configure.sh", privileged: false, keep_color: true
  end

end
